-- CRIANDDO TABLESPACE PARA O PROJETO ERP MULTIEMPRESA TESTE
CREATE TABLESPACE ERP_MULT_TST
    DATAFILE
    'D:\Udemy\Projeto_ERP_PLSQL\ERP_MULT_TST.dbf'
    SIZE 100M AUTOEXTEND ON NEXT 50M MAXSIZE 500M
    ONLINE
    PERMANENT
    EXTENT MANAGEMENT LOCAL AUTOALLOCATE
    SEGMENT SPACE MANAGEMENT AUTO;    
 
-- CRIANDO USUARIO
CREATE USER USER_TESTE
    IDENTIFIED BY USER_TESTE
    DEFAULT TABLESPACE ERP_MULT_TST
    TEMPORARY TABLESPACE TEMP;
    
-- CONCEDENDO PERMISSÕES PARA O USUÁRIO
GRANT ALL PRIVILEGES TO USER_TESTE;

-- ALTERANDO LIMITE DE COTA PARA O USUÁRIO
ALTER USER USER_TESTE QUOTA UNLIMITED ON ERP_MULT_TST;

-- CRIANDO TABLESPACE PARA O PROJETO BD ERP MULTIEMPRESA PRODUÇÃO
CREATE TABLESPACE ERP_MULTI_PROD
    DATAFILE
    'D:\Udemy\Projeto_ERP_PLSQL\ERP_MULT_PROD.dbf'
    SIZE 100M AUTOEXTEND ON NEXT 50M MAXSIZE 500M
    ONLINE
    PERMANENT
    EXTENT MANAGEMENT LOCAL AUTOALLOCATE
    SEGMENT SPACE MANAGEMENT AUTO;
    
-- CRIANDO USUÁRIO DE PRODUÇÃO
CREATE USER USER_PROD
    IDENTIFIED BY USER_PROD
    DEFAULT TABLESPACE ERP_MULTI_PROD
    TEMPORARY TABLESPACE TEMP;
    
-- CONCEDENDO PERMISSÕES PARA O USUÁRIO
GRANT ALL PRIVILEGES TO USER_PROD;
    
-- ALTERANDO LIMITE DE COTA PARA O USUÁRIO
ALTER USER USER_PROD QUOTA UNLIMITED ON ERP_MULTI_PROD;    

    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    